import express from 'express'

const app = express()
const port = 3000

// 상품 구매하기 API
app.post('/products/buy', (req, res) => {
    // 1. 가진 돈 검증하는 코드 (대략 10줄)
    // ...
    // ...
    // ...

    // 2. 판매여부 검증하는 코드 (대략 10줄)
    // ...
    // ...
    // ...

    // 3. 상품 구매하는 코드
    // ...
    // ...
    // ...
})

// 상품 환불하기 API
app.post('/products/refund', (req, res) => {
    // 1. 판매여부 검증하는 코드 (대략 10줄)
    // ...
    // ...
    // ...

    // 2. 상품 환불하는 코드
    // ...
    // ...
    // ...
})

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
})
