version: "3.7"

# 컴퓨터들
services:

  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/backend/index.js
      - ./email.js:/backend/email.js
    ports:
      - "4000:4000"

  my-database:
    image: mongo:5
    ports:
      - "27017:27017"